const playersBoys = [
  {
    id: 0,
    division: "U12",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 1,
    division: "U12",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 2,
    division: "U12",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 3,
    division: "U12",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 4,
    division: "U12",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 5,
    division: "U12",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 6,
    division: "U14",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 7,
    division: "U14",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 8,
    division: "U14",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 9,
    division: "U14",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 10,
    division: "U14",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 11,
    division: "U14",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 12,
    division: "U17",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 13,
    division: "U17",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 14,
    division: "U17",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 15,
    division: "U17",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 16,
    division: "U17",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
  {
    id: 17,
    division: "U17",
    firstName: "Jan",
    lastName: "Kowalski",
    position: "obrotowy",
  },
];

export default playersBoys;
